### ISSUE TITLE
Verze DSM

### ISSUE THREAD

**Issue by Meenya** [gabonator/Work-in-progress#1]
Na jakou verzi DSM je dělán plugin do Synology? Dlm, ani host mi nelze přidat, prý neplatný soubor.
Děkuju

**Comment by gabonator** [comment]
Ahoj, ak ti DSM ponuka moznost nainstalovat dlm plugin (nastavenia/hledani bt/pridat) a host plugin (nastavenia/hostovanie suborov/pridat) tak to musi fungovat. Mozno si iba zle stiahol plugin z githubu. Treba kliknut na ulozto.dlm a potom stiahnut kliknutim na tlacitko "raw", velkost suboru by mala byt 9.31kB a ulozto.host by mal mat 817 bajtov. Skontrolovat ci su spravne stiahnute mozes aj tak, ze ich skusis otvorit s WinRarom. Vovnutri je jeden subor "ulozto" a ked stlacis alt+v mal by ti ukazat konkretne zdrojove kody

**Comment by Meenya** [comment]
Ahoj, moc děkuji, opravdu jsem to špatně stahoval přes RMB. 
Nainstaloval jsem host, dlm, node.js i request, teď mi nejde spustit příkaz "node service.js" (jsem ve složce service přes telnet). Service.js ovšem ve složce "Service" není - zkoušel jsem spustit "node server.js", ale to háže chybu Unexpected token.

Netušíš, co zase dělám blbě? Předem díky

**Comment by gabonator** [comment]
1. **Nakopirovanie skriptu:**
   Predpokladam ze sa vies prihlasit na DSM cez sambu, (network sharing), tam si niekde vytvor adresar napr. "uloztoservice" a tam skopiruj tie subory z adresara service (dokopy 7 suborov). Ked budes cez telnet alebo ssh alebo putty prihlaseny na dsm, s pomocou prikazov "ls", "cd ..", "cd /", "cd", "pwd" sa dostan do adresara ktory si vytvoril. U mna je to "cd /volume1/shared/ulozto/service". Prikazom "ls" skontroluj ci tam naozaj je pritomny ten subor server.js. 
2. **Kontrola ci mas nainstalovany node js:**
   cez telnet zavolaj "node" a potom skus napisat "4+4" a malo by to vypisat hodnotu 8. Node vypnes ctrl+c, ctrl+c. Ak ho nemas nainstalovany, musis ist cez webove rozhranie do package managera (centrum balicku) a stiahnut balicek "node.js"
3. **Spustenie skriptu:**
   ak sme v spravnom adresari so skriptom, a nodejs mame nainstalovanyzavolame "node server.js", pravdepodobne to napise error: "Cannot find module 'request'", ten doinstalujeme zavolanim "npm install request".
4. **Otestovanie skriptu:**
   Otvor si http://diskstation:8034 cez webovy browser a skus nieco napisat do editboxu, mozes sledovat taktiez co robi konzola
5. **Spustenie servisu v pozadi**
   Ak ti server bezi, po odhlaseni z telnetu sa server vypne. Aby nam ostal bezat aj po odhlaseni, zavolame prikaz "nohup node server.js", samozrejme ze toto spustenie treba vykonat vzdy po restarte diskstationu, popripade to treba nejak nastavit aby sa to spustilo po starte

Ospravedlnujem sa ze to je tak komplikovane, mal som v plane ze ten servis prepisem do PHP a tym padom bude stacit nainstalovat len tie dva search pluginy. Som ale lenivy, no ked bude o to velky zaujem tak to skusim doprogramovat...

**Comment by Meenya** [comment]
1. Kde, prosím, najdu ten soubor "service.js", přesněji řečeno stáhnu? Ten jsem totiž ke stažení nenašel.

Určitě se není za co omlouvat, děláš to zadarmo a nikdo nemůže chtít, aby to bylo komfortní.

**Comment by gabonator** [comment]
Subory ku servisu su tuto: [SynologySearchEngine/Plugin/service](https://github.com/gabonator/Work-in-progress/tree/master/SynologySearchEngine/Plugin/service)

**Comment by Meenya** [comment]
Ale tam bohužel není soubor "service.js" :)

**Comment by gabonator** [comment]
preklep, mal to byt server.js :)

**Comment by Meenya** [comment]
Geniální, funguje! To vyhledávání je super, moc děkuju!
V popisu instalace určitě změň  "node service.js" na "node server.js", tam je totiž překlep a neustále jsem hledal service.js a já nejsem úplně bystrý :D
Samozřejmě jsem také bojoval s tím stahováním přes RAW u souborů js, než mi docvaklo stáhnutí přes RMB :D

Mohu tě nějak podpořit jako výraz díku?

**Comment by Meenya** [comment]
Ha, tak mi to stáhlo jeden soubor a u dalších to stáhne vždy jen okolo 40 kB a píše že velikost stahovaného souboru je těch 40 kB. Předpokládám, že se stahuje jen obrázek s captcha.

**Comment by Meenya** [comment]
Aha, neběžel server po zavření. Dal jsem znova nohup a už to fachá jak má :)

**Comment by gabonator** [comment]
Na vyraz diku sa mozes naucit programovat a vylepsit ten plugin :) Tuto nasu diskusiu som zapracoval do readme ku tomu projektu, tak snad to druhym pomoze bezproblemovo rozbehat tento plugin. Issue zatvaram ako uspesne fixnutu :)
