### ISSUE TITLE
Aktualizace DSM

### ISSUE THREAD

**Issue by Meenya** [gabonator/Work-in-progress#2]
Ahoj,

plugin běžel parádně do poslední aktualizace DSM. Nainstaloval jsem znova Node.js, ale tentokrát to už nepomohlo. Posílám odezvy na příkazy. Netušíš, co kde opravit? Děkuju

![1](https://cloud.githubusercontent.com/assets/17547868/14910152/4e3167ba-0deb-11e6-90db-6594e9014423.JPG)

**Comment by gabonator** [comment]
Skus updatovat node:
ipkg update
ipkg upgrade

**Comment by Meenya** [comment]
Píši to takhle dobře? Aktualizaci jsem provedl přes centrum balíčků.
![vystrizek](https://cloud.githubusercontent.com/assets/17547868/14937581/c294a254-0f0b-11e6-9d9c-6d0f3b11be6a.JPG)

**Comment by gabonator** [comment]
Aha, pomylil som sa. Synology pouziva dpkg a nie ipkg. Skus odinstalovat node a nainstalovat znova cez package manager

**Comment by Meenya** [comment]
Super, už to frčí. Stačilo opravdu odinstalovat a nainstalovat. Díky moc!

**Comment by Meenya** [comment]
Omlouvám se, ještě jeden dotaz. Když spustím "node server.js", tak se mi už nedaří spustit "nohup node server.js". Vykoná se to pouze v případě, že ukončím node pomocí ctrl+c, ctrl+c. Ale to už zase neběží server.js. Jak to mám správně udělat?

**Comment by svasek** [comment]
@Meenya Proste puste jen: "nohup node server.js &".
Pokud chces mit i log, tak to udelej treba takto: "nohup node server.js &> ulozto-log.txt &"

**Comment by Meenya** [comment]
Supr, pomohlo. Napoprvý se server ukončil po zavření telnetu, ale teď už ok. Díky
